import { Link } from 'react-router-dom';

export default function Landing(){
 return <div className="landing">
  <header className="landing-nav"><Link className="brand" to="/"><span className="brand-mark">T</span>TiffinFlow</Link><div><Link className="nav-link" to="/login">Login</Link><Link className="btn btn-dark" to="/register">Get started</Link></div></header>
  <section className="hero"><div className="hero-copy"><div className="eyebrow">SUBSCRIPTIONS • PAUSES • BILLING</div><h1>Run your tiffin service without the billing headache.</h1><p>Track customers, pause subscriptions for travel or festivals, and generate accurate monthly bills based only on the days you actually served.</p><div className="hero-actions"><Link className="btn btn-primary" to="/register">Start managing →</Link><a className="text-link" href="#features">Explore features</a></div><div className="trust-row"><span>✓ Real database</span><span>✓ REST APIs</span><span>✓ Pro-rated billing</span></div></div><div className="hero-card"><div className="mini-top"><span>September bill</span><span className="status-pill green">CALCULATED</span></div><h3>Rahul Sharma</h3><p className="muted">Standard Lunch • ₹3,000/month</p><div className="bill-grid"><div><small>Service days</small><strong>22</strong></div><div><small>Paused</small><strong>3</strong></div><div><small>Served</small><strong>19</strong></div></div><div className="amount"><span>Final bill</span><strong>₹2,590.91</strong></div></div></section>
  <section id="features" className="section"><div className="section-label">WHY TIFFINFLOW</div><h2>Everything a small tiffin business needs.</h2><div className="feature-grid"><Feature icon="01" title="Subscription control" text="Create monthly plans and subscriptions with clear start and end dates."/><Feature icon="02" title="Pause without overcharging" text="Pause periods automatically remove applicable weekday service days from billing."/><Feature icon="03" title="Accurate monthly bills" text="A transparent billing engine calculates served days, daily rate and final amount."/></div></section>
  <section className="audience"><div><div className="section-label">BUILT FOR</div><h2>Home-style tiffin owners who still manage everything in notebooks and spreadsheets.</h2></div><p>Search customers by phone, see who is active or paused, and keep billing history in one place. The product is deliberately simple so an owner can use it every day.</p></section>
  <section className="future section"><div className="section-label">NEXT ON THE ROADMAP</div><h2>Three features we would build next.</h2><div className="roadmap"><div><b>01</b><h3>Online payments</h3><p>Let customers pay monthly bills directly.</p></div><div><b>02</b><h3>WhatsApp reminders</h3><p>Send pause confirmations and bill notifications.</p></div><div><b>03</b><h3>Delivery tracking</h3><p>Record daily deliveries and missed tiffins.</p></div></div></section>
  <footer><span>© 2026 TiffinFlow</span><span>Built for local food businesses.</span></footer>
 </div>
}
function Feature({icon,title,text}){return <article className="feature-card"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>}
